### ISSUE TITLE
Link/Button plugin (File link) - add extension and filesize information

### ISSUE THREAD

**Issue by aacimov** [django-cms/djangocms-frontend#215]
**Is your feature request related to a problem? Please describe.**
When using a link that points to a file (file_link) It is always helpful seeing the extension and filesize of the file provided.

**Describe the solution you'd like**
I would like to show the attached file extension and filesize so the users have the additional info about the file provided and choose which file they would like to download (in some cases there are "machine readable" files and "user readable" files with the same name and of different type (e.g. CSV and PDF).

**Additional context**
I am using Django 4.2.11 with Django CMS 4.1.0 and djangocms_frontend 1.3.1.

**Comment by fsbraun** [comment]
Hi @aacimov ! I assume you are **not looking for a link plugin** here, since the link plugin in general allows to be wrapped around any display text.

Do I understand that you are looking for a **file download plugin** that offers users files with different options on how those files are displayed (e.g., icon + name + size, or name + type + size, or whatever)? Did you have a look at https://github.com/django-cms/djangocms-file ?  Do you need additional functionality?

**Comment by aacimov** [comment]
Oh, I was certain that djangocms_frontend will take care of all of these since by using Templates and/or manipulating the templates you could do just about anything.

I am rather concerned that in the future djangocms_filer will be a "holy grail" of all frontend manipulations in the CMS so I was being (obviously) proactive :D

Definitely downloading the djangocms-file.

**Comment by fsbraun** [comment]
I'm not sure I understand... 🤷‍♂️

**Comment by aacimov** [comment]
@fsbraun never mind, downloaded the djangocms-file plugin, closing this.
